### ISSUE TITLE
window manager crash

### ISSUE THREAD

**Issue by netfun81** [tleino/mxswm#1] opened 2021-12-06 01:28 UTC
Interesting window manager concept, I did experience some crashes when using two stacks and using the hide stack function as a way to fullscreen one stack.  Also, will you be adding a way to delete a window in the future? instead of just removing a stack.   Thanks, good work so far.

**Comment by tleino** [comment] 2021-12-06 09:50
Hi, the hide stack function has some known issues (not crashes, but issues with focus) -- will fix asap. Yes, I will add a delete window feature :) Crashes are very much expected because many X11 clients use the X11 protocol in weird ways and I have tested the window manager only with the programs that I use.

I might also return back to tracking windows from MapRequest event instead of CreateNotify. That is how I do it in cocowm and how most other window managers do it, and that itself might fix some crashes. The crashes that happen in mxswm should be crashes caused by not having a built-in error handler for X11 protocol errors and those are often a little harder to fix (due to asynchronous nature) than e.g. segmentation fault-crashes. Adding an error handler would of course take those "crashes" away, but would not help fixing the actual problem. If you get segfaults, I can probably fix them very fast. In either case please submit details and I will see. If you want to help in fixing, you can compile mxswm with -DTRACE and send the output, or a patch ;)

In the future I might combine cocowm and mxswm to one window manager, or keep them separate. I have not yet decided. The cocowm window manager also has a compile-time flag, -DWANT_ONE_PER_COLUMN, that enables mxswm-like behavior, however mxswm is a bit more recent and has the client menu. 

I am constantly exploring and trying to find the optimal balance of things. These are at the moment very much work in progress, even though I am currently using mxswm on all of my computers for all tasks, but not using the hide-feature as much as I would like to -- I have to fix it before using it :) I really like the hide-feature and would want to polish it :)

**Comment by tleino** [comment] 2021-12-06 15:55
I added the delete window feature quickly. I still need to improve it with the ICCCM DELETE_WINDOW protocol for supporting the "Are you sure"-dialogs.

**Comment by tleino** [comment] 2021-12-19 12:34
You can also run mxswm with sync option for debugging the problems, see commit 98c56990f7f6ab1a3d46a5e80cd297c58b3f8882.

**Comment by netfun81** [comment] 2021-12-19 18:46
I think the cause of the crash I was experiencing, is that when hiding a stack of programs, a program in that stack can steal focus from the focused main stack.  Then if unhiding the hidden stack while the main stack is unfocused it causes the window manager to close.  Is there is a way to prevent hidden stack programs from stealing focus from the main focused stack?

**Comment by tleino** [comment] 2021-12-19 19:11
Thanks for this report -- I will look into the problem from this focus issue perspective. I want to get it fixed, too :)

**Comment by tleino** [comment] 2021-12-19 20:25
I fixed one focus issue: dc6f3051df8737ffe964af37baa980f44d4458c2 -- will see if I find more issues, but of course chances are this fixed your issue already? 

I have one more known issue related to hiding, but that issue also requires the use of sticky stacks, and this issue is not related to sticky stacks.

**Comment by tleino** [comment] 2021-12-19 23:08
I fixed all issues that I could think of being related to this issue, based on my own testing and and based on your report. For the focus/hide-mode issues, I committed these: 74edd87c0c1e9a67808e0ebb2019ddd57b290528 046eb096dabd62143157506d0940c809ff916f49 2659031db479a24b3c9153bf8128a25247a02407 dc6f3051df8737ffe964af37baa980f44d4458c2.

Earlier, I committed patches 618620cdcf6bfc0003efd459f870a983dd757abf 847346c65910def16f8ea3f163783aaeba4d2d92 581ca28aab108ee4a4fdd8981f8b4efdd216fe3f for the delete window feature, which is now completely implemented, satisfying the feature request.

You can reopen / file a new report if this did not fix the issues you were seeing. Feel free to also file more feature requests.

**Closed as completed by tleino** 2021-12-19 23:08 UTC
Labels: bug, enhancement
